trigger:
- main

pool:
  name: 'default'
  vmImage: 'agent1'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'mayaServiceConnection'
    resourceGroupName: 'mayaResourceGroup'
    location: 'northeurope'
    templateLocation: 'Linked artifact'
    csmFile: 'storageTemplate.json'
