trigger:
- main

pool:
  name: 'default'
  vmImage: 'agent1'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'mayaServiceConnect'
    subscriptionId: 'a8108c2b-496c-424d-8347-ecc8afb6384c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mayaResourceGroup'
    location: 'francecentral'
    templateLocation: 'Linked artifact'
    csmFileLink: 'storageTemplate.json'
    #csmFileLink: '$(AzureFileCopy.StorageContainerUri)templates/mainTemplate.json$(AzureFileCopy.StorageContainerSasToken)'
    #csmParametersFileLink: '$(AzureFileCopy.StorageContainerUri)templates/mainTemplate.parameters.json$(AzureFileCopy.StorageContainerSasToken)'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'mayaServiceConnection'
    ScriptType: 'FilePath'
    ScriptPath: './Deploy-AzTemplate.ps1'
    ScriptArguments: -Location 'centralus' -ResourceGroupName 'demogroup' -TemplateFile templates\mainTemplate.json
    azurePowerShellVersion: 'LatestVersion'

