trigger:
- main

pool:
  name: 'default'
  vmImage: 'agent1'

steps:
- task: AzurePowerShell@3
  displayName: 'Create storage accounts'
  inputs:
    azureSubscription: 'mayaARMServiceConnection'
    ScriptType: 'FilePath'
    FilePath: 'deployStorage_Server.ps1'
