trigger:
- main

pool:
  name: 'default'
  vmImage: 'agent1'

steps:
- task: AzurePowerShell@3 # Create two storage accounts and a windows server
  displayName: 'Create storage accounts and windows server'
  inputs:
    azureSubscription: 'mayaServiceConnect'
    ScriptType: 'FilePath'
    FilePath: 'deployStorageAndServer.ps1'
    
- task: CopyFiles@2 # Copy the script to the virtual machine
  inputs:
    SourcePath: 'copyBlobs.ps1'
    TargetPath: 'C:\\copyBlobs.ps1'
    azureSubscription: ${{ secrets.SUBSCRIPTION_ID }}
    machineName: 'simple-vm'

- task: AzureVM@2 # Run the command on the virtual machine
  inputs:
    azureSubscription: ${{ secrets.SUBSCRIPTION_ID }}
    vmName: 'simple-vm'
    commandToExecute: 'powershell C:\\copyBlobs.ps1' 
    
