name: deployArmTemplate
 
trigger: none
 
pr: none
 
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'tamopsarm'
                  subscriptionId: 'a8108c2b-496c-424d-8347-ecc8afb6384c'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'mayaResourceGroup'
                  location: 'northeurope'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/storageTemplate.json'
                  deploymentMode: 'Incremental'
